/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Serveur_CheckIn;

import static divers.Config_Applic.pathConfig;
import divers.Persistance_Properties;
import java.io.IOException;
import java.net.Socket;
import java.sql.SQLException;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author damien
 */
public class FenAppServeur extends javax.swing.JFrame {
    private Properties myProperties;
    
    private int port;
    private int port_admin;
    private String IP;
    
    private int nbr_client;
    private ThreadServeur ts;
    
    private int port_carte;
    private String ip_carte;
    /**
     * Creates new form FenAppServeur
     */
    public FenAppServeur() {
        initComponents();        
        System.out.println("Serveur / initialisation / main");
        myProperties = Persistance_Properties.LoadProp(pathConfig);
        
        //recuperation du port dans l'objet properties
        port = Integer.parseInt(myProperties.getProperty("port"));
        jLabel_port.setText(Integer.toString(port));
        
        port_admin = port+1;
        jLabel_port_admin.setText(Integer.toString(port_admin));
        
        System.out.println("serveur / acquisition du port / main"); 
        
        //nb max client
        nbr_client = Integer.parseInt(myProperties.getProperty("nbr_client"));
        jLabel_nbr_client.setText(Integer.toString(nbr_client));
        
        IP = myProperties.getProperty("ip");
        jLabel_addresse_ip.setText(IP);
        
        ip_carte = myProperties.getProperty("ip_carte");
        port_carte = Integer.parseInt(myProperties.getProperty("port_carte"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton_start = new javax.swing.JButton();
        jButton_stop = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel_port_ecoute = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel_nbr_client = new javax.swing.JLabel();
        jLabel_port = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel_addresse_ip = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel_port_admin = new javax.swing.JLabel();
        jCheckBox_to_card = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setText("Serveur");

        jLabel2.setForeground(new java.awt.Color(51, 102, 255));
        jLabel2.setText("Port d'écoute: ");

        jButton_start.setText("Start");
        jButton_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_startActionPerformed(evt);
            }
        });

        jButton_stop.setText("Stop");
        jButton_stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_stopActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(51, 102, 255));
        jLabel4.setText("Nombre de clients maximum :");

        jLabel_nbr_client.setForeground(new java.awt.Color(51, 102, 255));
        jLabel_nbr_client.setText("XX");

        jLabel_port.setForeground(new java.awt.Color(51, 102, 255));
        jLabel_port.setText("XX");

        jLabel6.setForeground(new java.awt.Color(51, 102, 255));
        jLabel6.setText("Addresse IP :");

        jLabel_addresse_ip.setForeground(new java.awt.Color(51, 102, 255));
        jLabel_addresse_ip.setText("XX");

        jLabel3.setForeground(new java.awt.Color(51, 102, 255));
        jLabel3.setText("Port d'administration : ");

        jLabel_port_admin.setForeground(new java.awt.Color(51, 102, 255));
        jLabel_port_admin.setText("XX");

        jCheckBox_to_card.setText("Connect to CARD");
        jCheckBox_to_card.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_to_cardActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(79, 79, 79)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel_port))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel6))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel_nbr_client, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel_port_ecoute, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel_addresse_ip))))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel_port_admin))))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(129, 129, 129)
                            .addComponent(jButton_start)
                            .addGap(90, 90, 90)
                            .addComponent(jButton_stop))))
                .addContainerGap(79, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jCheckBox_to_card)
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel1))
                    .addComponent(jCheckBox_to_card))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel_port_ecoute))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel_port))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel_port_admin))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel_nbr_client))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel_addresse_ip))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_start)
                    .addComponent(jButton_stop))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_stopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_stopActionPerformed
        try {
            ts.getInstruc().close();
            ts.getSSocket().close();
            ts.getSocket_carte().close();
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(FenAppServeur.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(FenAppServeur.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton_stopActionPerformed

    private void jButton_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_startActionPerformed
        jButton_start.setEnabled(false);
        System.out.println("serveur / Demarrage du serveur / main");
        Socket Sock = null;
        if(jCheckBox_to_card.isSelected())
        {    
            try {

                //socket vers le serveur carte
                Sock = new Socket(ip_carte, port_carte);
                
                System.out.println("serveur / Connexion serveur carte / main");
                
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "Connexion au serveur carte impossible", "Serveur carte erreur", JOptionPane.ERROR_MESSAGE);
            }
        }
        ts = new ThreadServeur(port, nbr_client, new ListeTaches(), Sock);
        ts.start();
        
    }//GEN-LAST:event_jButton_startActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            ts.getInstruc().close();
            ts.getSSocket().close();
            ts.getSocket_carte().close();
            ts.stop();
        } catch (SQLException ex) {
            Logger.getLogger(FenAppServeur.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(FenAppServeur.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_formWindowClosing

    private void jCheckBox_to_cardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_to_cardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_to_cardActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenAppServeur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenAppServeur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenAppServeur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenAppServeur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenAppServeur().setVisible(true);
            }
        });
    }


    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_start;
    private javax.swing.JButton jButton_stop;
    private javax.swing.JCheckBox jCheckBox_to_card;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel_addresse_ip;
    private javax.swing.JLabel jLabel_nbr_client;
    private javax.swing.JLabel jLabel_port;
    private javax.swing.JLabel jLabel_port_admin;
    private javax.swing.JLabel jLabel_port_ecoute;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
